[2024-06-18T01:29:49.271+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T01:29:49.378+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.carregar_dados scheduled__2024-06-17T23:30:00+00:00 [queued]>
[2024-06-18T01:29:49.402+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dados_climaticos_estruturados.carregar_dados scheduled__2024-06-17T23:30:00+00:00 [queued]>
[2024-06-18T01:29:49.404+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-18T01:29:49.464+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): carregar_dados> on 2024-06-17 23:30:00+00:00
[2024-06-18T01:29:49.554+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=209) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-18T01:29:49.568+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dados_climaticos_estruturados', 'carregar_dados', 'scheduled__2024-06-17T23:30:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/weather/custom_dags/dados_climaticos_estruturados.py', '--cfg-path', '/tmp/tmpjwxvq8ia']
[2024-06-18T01:29:49.577+0000] {standard_task_runner.py:63} INFO - Started process 240 to run task
[2024-06-18T01:29:49.577+0000] {standard_task_runner.py:91} INFO - Job 52: Subtask carregar_dados
[2024-06-18T01:29:50.284+0000] {task_command.py:426} INFO - Running <TaskInstance: dados_climaticos_estruturados.carregar_dados scheduled__2024-06-17T23:30:00+00:00 [running]> on host bd8fdde9baa6
[2024-06-18T01:29:50.972+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dados_climaticos_estruturados' AIRFLOW_CTX_TASK_ID='carregar_dados' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T23:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T23:30:00+00:00'
[2024-06-18T01:29:50.977+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T01:29:58.271+0000] {logging_mixin.py:188} INFO - Pinged your deployment. You successfully connected to MongoDB!
[2024-06-18T01:29:58.272+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-18T01:29:58.273+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T01:29:58.284+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dados_climaticos_estruturados, task_id=carregar_dados, run_id=scheduled__2024-06-17T23:30:00+00:00, execution_date=20240617T233000, start_date=20240618T012949, end_date=20240618T012958
[2024-06-18T01:29:58.338+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-18T01:29:58.352+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T01:29:58.354+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
